services:
  bot:
    build: .
    container_name: ptb-nn
    restart: unless-stopped
    env_file:
      - .env # .env is only read with "compose up"
    volumes:
      - ./bot:/bot
    environment:
      CONTAINER: "true"
      PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
